package src.Exception_Handling;

public class Practice {
    public static void main(String[] args) {
        int a = 10;
        int b = 0;

        int result = 0;

        String name = "teja";


        try {

            result = a / result;

        } catch (Exception e) {


            System.out.println("Exception handled here");


        }


    }


}
